### ISSUE TITLE
Ignoring exception in command meep. 

### ISSUE THREAD

**Issue by EnzoDiazDev** [zero-files/otherworld#1]
Cuando enviás un comando privado a un canal normal. 

Envía un mensaje a un canal distinto a la mensajería privada del bot, con el comando `!meep` o con cualquier otro `dm_commande`. 

`discord.ext.commands.errors.PrivateMessageOnly: This command can only be used in private messages.`

**Comment by camarelle-c** [comment]
discord.ext.commands.errors.PrivateMessageOnly exceptions are now ignored
